# Generated by Django 4.2.7 on 2025-05-10 11:40

import ats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='applicant_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='file_hash',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='job_data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='resume',
            field=models.FileField(upload_to=ats.models.resume_upload_path),
        ),
        migrations.AlterUniqueTogether(
            name='resumeanalysis',
            unique_together={('file_hash', 'job_data')},
        ),
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='job_id',
        ),
    ]
